### ISSUE TITLE
jshint options are not being used properly

### ISSUE THREAD

**Issue by leon** [sbt/sbt-jshint#13]
I've got quite a large .jshintrc that I've been using for a large angular project which works great with gulp-jshint

    {
        "node": true,
        "browser": true,
        "esnext": true,
        "bitwise": true,
        "camelcase": true,
        "curly": true,
        "eqeqeq": true,
        "immed": true,
        "indent": 2,
        "latedef": true,
        "newcap": true,
        "noarg": true,
        "quotmark": "single",
        "regexp": true,
        "undef": true,
        "unused": true,
        "strict": true,
        "trailing": false,
        "smarttabs": true,
        "white": false,
        "globals": {
            "$": false,
            "jQuery": false,
            "angular": false,
            "browser": false,
            "repeater": false,
            "element": false,
            "inject": false,
            "afterEach": false,
            "beforeEach": false,
            "confirm": false,
            "context": false,
            "describe": false,
            "ddescribe": false,
            "expect": false,
            "it": false,
            "iit": false,
            "jasmine": false,
            "JSHINT": false,
            "mostRecentAjaxRequest": false,
            "qq": false,
            "runs": false,
            "spyOn": false,
            "spyOnEvent": false,
            "waitsFor": false,
            "xdescribe": false,
            "URI": false,
            "_": false,
            "input": false,
            "sleep": false,
            "pause": false,
            "protractor": false,
            "moment": false,
            "i18n": false,
            "by": false
        }
    }

I then simply added i minimal angular directive to app/assets/directives/myDirective.js

    angular.module('mydirective', []).directive('myDirective', function () {
      'use strict';

      return {
        link: function (scope, element) {
          element.text('Hello World');
        }
      };
    });

When I then run jshint from the sbt console it complains that angular is undefined even though angular is defined as a global in .jshintrc.

Running jshint via node doesn't produce an error so it must be either the version of jshint that is used. the node version I have installed is 2.5.1 whilst sbt-jshint uses 2.4...
or how it passes the options to node.

**Comment by micmro** [comment]
You can us `predef` instead, that did the trick for me:

```
{
	"browser" : true,
	"maxerr" : 10,
	
	"jquery" : true,
	"laxcomma" : true,
	"loopfunc" : true,
	"curly" : true,
	"latedef" : true,
	"quotmark" : "double",
	"undef" : true,
	"maxdepth" : false,
	"predef" : ["define", "require""]
}
```

**Comment by huntc** [comment]
Thanks. @leon can you confirm whether this resolves your issue?

**Comment by leon** [comment]
@huntc I went over to using gulp, so I haven't got a project that uses sbt-jshint at the moment :(

**Comment by huntc** [comment]
No worries. Closing for now.

**Comment by rkrzewski** [comment]
I've verified that using `predef` instead of `globals` as suggested by @micmro indeed fixes the problem. Thanks!
