### ISSUE TITLE
.jshintrc not stripped from comments

### ISSUE THREAD

**Issue by eamelink** [sbt/sbt-jshint#19]
The regular cli runner strips comments from the `.jshintrc` file before parsing it as JSON: https://github.com/jshint/jshint/blob/55999d2bec709a6bba45be860276fbd08129ce31/src/cli.js#L531

This plugin doesn't do that, so a `.jshintrc` file with comments breaks at:

```
com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: SyntaxError: Unexpected token: / (/Users/eamelink/projects/sbt-jshint-minimal/project/target/jshint/jshint-shell.js#30)   at /Users/eamelink/projects/sbt-jshint-minimal/project/target/jshint/jshint-shell.js:30 (anonymous)
```

**Comment by chinmaybijwe** [comment]
Hey Chris, 
Just wondering, do you guys plan to publish the next version of sbt-jshint sometime soon?

**Comment by huntc** [comment]
@chinmaybijwe Yes of course - my apologies - I'll do it now.

**Comment by huntc** [comment]
`1.0.3` is now published

**Comment by chinmaybijwe** [comment]
Thank you! :)

On Monday, January 26, 2015, Christopher Hunt <notifications@github.com>
wrote:

> 1.0.3 is now published
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sbt/sbt-jshint/issues/19#issuecomment-71565125>.
>


-- 
Chinmay

**Comment by benmccann** [comment]
It looks like this was fixed. Feel free to reopen if that's incorrect
