### ISSUE TITLE
Please bump to the latest jslint-node webjar 2.6.3

### ISSUE THREAD

**Issue by fdietze** [sbt/sbt-jshint#27]
"org.webjars" % "jshint-node" % "2.6.3"

**Comment by fdietze** [comment]
I sent a pull request: https://github.com/sbt/sbt-jshint/pull/28

**Comment by tiagoengel** [comment]
+1
jshint-node is obsolete now. Why not use the latest version on npm instead?

**Comment by benmccann** [comment]
Currently using "org.webjars.npm" % "jshint" % "2.9.3"
