### ISSUE TITLE
Some trouble with ES6/esnext syntax (template strings)

### ISSUE THREAD

**Issue by kirinmurphy** [sbt/sbt-jshint#32]
Hi, 
I am using sbt-jshint (v 1.0.3) on a project that is using ES6. 
I have "esnext: true", set in my .jshintrc file and am using a number of ES6 conventions successfully. 

When attempting to use Template Strings (Template Literals), jshint doesn't recognize the backticks and errors with: 

**Unexpected '`'**

I haven't tested the latest native jshint but according to this thread it looks like backtick support was added a while back.  Any thoughts on why this fails? 

https://github.com/jshint/jshint/issues/1219

Thanks.

**Comment by mkurz** [comment]
v1.0.3 was using jshint 2.4.3, but the feature you are asking for was added in jshint 2.5.0 [here](https://github.com/jshint/jshint/commit/164d0effbe1db69e3e8cce5f87bfb35c80045e37).
I just released [version 2.0.0](https://github.com/sbt/sbt-jshint/releases/tag/2.0.0) which uses latest jshint version available, so this can now be seen as resolved.
