### ISSUE TITLE
outdated jshint

### ISSUE THREAD

**Issue by mberndt123** [sbt/sbt-jshint#34]
Hey,

The jshint version sbt-jshint uses (2.4.1) is outdated, the current version is 2.9.2. Just bumping the dependency version didn't seem to work as it doesn't find the lodash library, even if I add it as an additional dependency. How does sbt-jshint know which webjars to unpack anyway? Because it worked fine back when jshint was using underscore rather than lodash…

**Comment by benmccann** [comment]
I just merged a PR to bump it to 2.6.3-2

**Comment by genachka** [comment]
+1 to update to newer 2.9.2 version.

**Comment by huntc** [comment]
Are there massive benefits to upgrade at this point? Jshint is working great for me as-is.

**Comment by genachka** [comment]
From brief skim of the change log there's lots of bug fixes and much better ES6 support.

**Comment by huntc** [comment]
If someone can do the PR then I will review/merge/release.

**Comment by koppor** [comment]
Done in #36. Seemed to be easy. Hope, that I did not overlook something.

**Comment by koppor** [comment]
I now discovered the same issue as @mberndt123 (see https://travis-ci.org/sbt/sbt-jshint/builds/160997285)

No idea how to solve.

```
info] [info] Done updating.

[info] [info] JavaScript linting on 1 source(s)

[info] [error] 

[info] [error] module.js:340

[info] [error]     throw err;

[info] [error]           ^

[info] [error] Error: Cannot find module './scope-manager.js'

[info] [error]     at Function.Module._resolveFilename (module.js:338:15)

[info] [error]     at Function.Module._load (module.js:280:25)

[info] [error]     at Module.require (module.js:364:17)

[info] [error]     at require (module.js:380:17)

[info] [error]     at Object.<anonymous> (/tmp/sbt_4fe3dbc7/test/project/target/node-modules/webjars/jshint/src/jshint.js:44:20)
```

**Comment by koppor** [comment]
I updated jshint from `jshint-node` to `jshint` and all tests go through in #31. Maybe someone else can double check?

**Comment by benmccann** [comment]
Currently using "org.webjars.npm" % "jshint" % "2.9.3"
